Point to mainnet for vercel previews
Axion-Network/axion-frontend-1 pull request #11
Opened 2020-11-20 19:00 UTC by Mvii7

2020-11-20 20:08 UTC, Vicarious1 approved these changes

2020-11-21 04:39 UTC, Dellybro approved these changes

2020-11-21 09:26 UTC, AudioSin requested changes
I will be changing this so we switch based on an environment variable. Doesnt make sense we set production: true by default.

2020-11-21 11:26 UTC, Mvii7 commented
> I will be changing this so we switch based on an environment variable. Doesnt make sense we set production: true by default.

done

2020-11-23 07:56 UTC, closed without merging