Fix bpd check boxes
Axion-Network/axion-frontend-1 pull request #9
Opened 2020-11-20 14:31 UTC by Vicarious1

- Check for end of BPD period plus 1 day in milliseconds when checking to see if a stake meets the BPD criteria

I think this logic checks out, but it's is tough to test on current testnet since it has very short days.

2020-11-21 21:12 UTC, Vicarious1 commented on src/app/staking-page/staking-page.component.ts
> +    return this.formsData.depositDays > 349 &&
Ideally i'd have written a unit test that validates this for each BPD, but the unit tests are broken right now. Maybe that's something I can work on at some point

2020-11-23 07:58 UTC, AudioSin approved these changes

2020-11-23 08:00 UTC, AudioSin commented
@Vicarious1 Can this be merged?

2020-11-23 12:28 UTC, Mvii7 approved these changes
Tested, 349 days doesn't check BPD 1, dunno how it will behave after BPD 1 but is good for now

2020-11-23 12:30 UTC, Mvii7 requested changes

2020-11-23 12:30 UTC, Mvii7 commented on src/app/staking-page/staking-page.component.ts
> +const SECONDS_PER_DAY = 86400000;
Pls get this from settings

2020-11-23 12:31 UTC, Mvii7 commented on src/app/staking-page/staking-page.component.ts
> +const SECONDS_PER_DAY = 86400000;
Also its 86400 per day ¯\_(ツ)_/¯

2020-11-23 12:56 UTC, Mvii7 approved these changes

2020-11-23 14:01 UTC, merged